stage-0
RUN python -m pip install --upgrade pip
135ms
/root/.nix-profile/bin/python: No module named pip
Dockerfile:20
-------------------
18 |     ENV NIXPACKS_PATH=/opt/venv/bin:$NIXPACKS_PATH
19 |     COPY . /app/.
20 | >>> RUN --mount=type=cache,id=s/ae5419d6-64cc-424e-b45e-5826d6ca4000-/root/cache/pip,target=/root/.cache/pip python -m pip install --upgrade pip
21 |     RUN --mount=type=cache,id=s/ae5419d6-64cc-424e-b45e-5826d6ca4000-/root/cache/pip,target=/root/.cache/pip python -m pip install -r requirements.txt
22 |
-------------------
ERROR: failed to build: failed to solve: process "/bin/bash -ol pipefail -c python -m pip install --upgrade pip" did not complete successfully: exit code: 1
Error: Docker build failed
